Repository FachschaftMathPhysInfo/Programmiervorkurs, pull requests merged in 2025-04, with the labels that each got.

#157 Fix compile workflow
  .github/workflows/build.yml
  .github/workflows/build_and_test.yml
  .gitignore
  appendix/cheatsheet_shellcomands.tex
  appendix/cheatsheet_shortcuts.tex
  appendix/error_messages.tex
  appendix/intro.tex
  eigener_computer/intro.tex
  eigener_computer/linux.tex
  eigener_computer/macos.tex
  eigener_computer/windows.tex
  files/array.cpp
  lektionen/arithmetics.tex
  lektionen/arrays.tex
  lektionen/arrays_vectors.tex
  lektionen/compiling.tex
  lektionen/control_flow.tex
  lektionen/debbugging.tex
  lektionen/errors_warnings.tex
  lektionen/exercises/intro.tex
  lektionen/functions.tex
  lektionen/input_output_hello_world.tex
  lektionen/intro.tex
  lektionen/loops.tex
  lektionen/recursion.tex
  lektionen/stdlib.tex
  lektionen/unix_shell.tex
  lektionen/variables_datatypes.tex
  lektionen/vectors.tex
  vorkurs.tex
Labels: bug, fix_before_vorkurs25

#151 [Appendix] Added Fizzbuzz
  .github/workflow/build_and_test.yml
  appendix/coding_style.tex
  files/fizzbuzz.cpp
  files/fizzbuzz_pretty.cpp
  lektionen/arrays_vectors.tex
Labels: enhancement

#164 Fix broken links
  folien_abschied/folien_abschied.tex
  lektionen/arrays_vectors.tex
  lektionen/errors_warnings.tex
  lektionen/stdlib.tex
  lektionen/tictactoe.tex
  lektionen/unix_shell.tex
  lektionen/vectors.tex
  orgakram/ansible.cfg
Labels: bug, fix_before_vorkurs25

#165 Add compilation tests
  .github/workflows/build_and_test.yml
  .github/workflows/test_scripts/check_compilability.py
  .github/workflows/test_scripts/check_links.py
Labels: enhancement, fix_before_vorkurs25, testing
